project:
  type: book

book:
  title: "Dotnet Notes"
  author: "Kittipos Sirivongrungson"
  date: today
  repo-url: https://github.com/Lightbridge-KS/dotnet-notes
  site-url: https://dotnet-notes-lightbridge.netlify.app
  chapters:
    - index.qmd
    - part: Intro
      chapters: 
        - "content/ecosystem/dotnet-eco.qmd"
    - part: C# Lang
      chapters: 
        - "content/basic/syntax-basic-cheatsheet.qmd"
        - "content/basic/cs_flow_control.qmd"
        - "content/basic/cs_iteration.qmd"
        - "content/basic/cs_attributes.qmd"
        - "content/basic/cs_linq.qmd"
        - "content/orgs/cs_program.qmd"
        - "content/basic/cs_code_docs.qmd"
        - "content/datatypes/cs_attribute.qmd"
        - text: Proprocessor Directive
          href: "content/basic/cs_proprocessor-directive.qmd"
    - part: Organization
      chapters: 
        - "content/orgs/cs_orgs.qmd"
        - "content/orgs/cs_code-organization.qmd"
        - "content/orgs/cs_naming_conv.qmd"
    - part: Data, Types, Interface
      chapters: 
        - "content/basic/cs_datatypes.qmd"
        - "content/datatypes/datatypes_numeric.qmd"
        - "content/datatypes/cs_dictionary.qmd"
        - "content/datatypes/interface_IEnumerable.qmd"
        - "content/basic/cs_stack.qmd"
        - "content/datatypes/cs_enums.qmd"
    - part: Event
      chapters: 
        - text: Even Subscription
          href: "content/event/event-subscription.qmd"
    - part: OOP
      chapters: 
        - "content/oop/cs_classes.qmd"
        - "content/oop/cs_classes_nested.qmd"
        - "content/oop/cs_type-inferred-object-creation.qmd"
        - "content/oop/cs_record.qmd"
        - text: Sealed Class
          href: "content/oop/cs_sealed_class.qmd"
        - "content/oop/cs_methods.qmd"
        - "content/oop/cs_methods_overloading.qmd"
        - "content/oop/cs_method_calling_order.qmd"
    - part: Data Conversion
      chapters: 
        - "content/conversion/cs_json.qmd"
    - part: Validation
      chapters: 
        - "content/validate/record_validation.qmd"
        - "content/validate/DataAnnotations-CheatSheet.qmd"
        - "content/validate/DataAnnotations-Validate.qmd"
    - part: Environment
      chapters: 
        - "content/environment/env-management.qmd"
        - "content/environment/config-injection-pipeline.qmd"
    - part: EF Core
      chapters: 
        - "content/EF/ef-core-basic.qmd"
    - part: Testing
      chapters: 
        - "content/tests/cs_unittest.qmd"
        - "content/tests/cs_testrepo-architect.qmd"
        - "content/tests/cs_xUnit.qmd"
        - "content/tests/cs_xUnit-cheatsheet.qmd"
        - "content/tests/cs_moq_basic.qmd"
    - part: .NET Interative
      chapters: 
        - "content/interactive/dotnet-interactive.qmd"
    - part: CLI
      chapters: 
        - "content/basic/cs_cli-args.qmd"
    - part: DotNet Apps
      chapters: 
        - "content/app/dotnet-mvc.qmd"
        - "content/app/dotnet-react.qmd"
        - "content/app/dotnet-react-ex.qmd"
        - text: MAUI Blazor App
          href: "content/app/dotnet-maui-blazor.qmd"
        - text: MAUI Blazor App - Setup
          href: "content/app/dotnet-maui-blazor-setup.qmd"
    - part: DotNet WebAPI
      chapters: 
        - "content/models/model_DTO_table.qmd"
        - "content/models/webapi_controller-vs-minimal.qmd"
    - part: Blazor
      chapters: 
        - "content/blazor/basic/blazor-repo-architect.qmd"
        - "content/blazor/basic/razor-syntax.qmd"
        - "content/blazor/basic/blazor-compose-component.qmd"

format:
  html:
    theme:
      light:
      - cosmo
      dark: 
      - darkly
    toc-depth: 4

freeze: auto